language: ruby
rvm:
 - 2.2.2

services:
  - postgresql

script:
  - bundle exec rake db:test:prepare
  - bundle exec rake
cache: bundler


deploy:
  provider: heroku
  api_key:
    secure: DrgDaQwzdeTeIZ6T/0kTudA+Hy4Jh+Ma+6Nj1mnlUaR2nY7nJ1GBSQRwHHaUHkgOZ9JcvCHYnb0GsHFtBPeTAmsVjswxAijflO3mBQhfY6TTu5QUL1Jqz9vSU2WJAvdAODi6dVg7HgIiOMDyT8xr2kK8BZE99MAanvQhS4kzHH+ceJjq6bwUivLawLmn1dAk4D7f1ounAKnGL69gkYfP/XlJL2yYJaUNgOIKhDk49hrLMl3GlNlqq71wzAmt43ngu+oEy20xXww0DAQesG/g73oFhburcfxwWtTOET12w+TTod1BrRa6sr9Y4VnlcYx5u0lDUQ/gimiwrITS+UOZ6Nb3ij7xQh1JfJO+3nE6OJTbCe3X4tB2czXChKyX+Y0U/RomUQ8BUmYcszL7xysOl5AXxax152pMZDXAL3W2HYCeEjK+kCSaWgLI8ZyyyK9bE+4byISWjAfySxQukdyDaoPheXylZyqyQEWwcZbp/km2UU0eWh38141H5O145pf5PwvADJ+ckoBQGS9bXthR1+LIenm2si9rUhSbtMT6zT58ADufNxiRSk5GjN+YIFHl2MsOMDLb4LpkkXa4VC2VXFX4ona2KlEHI1c30FUiDMtNiIvMNoicRYWZOoQW3B0hcc4Pt2wXE0PPOvMsJOsxCYiLcYqr0ZfVDMquSbY8Lxs=
  app: the_pivot
  on:
    repo: ThePivotHJJJ/the_pivot
